### ISSUE TITLE
golang .so build?

### ISSUE THREAD

**Issue by steve-jansen** [hashicorp/vault-ssh-helper#1]
Hi @vishalnayak,

This README note intrigued me:

> PAM modules are supposed to be shared object files and Go (currently) does not support creation of .so files. It was a choice between writing a PAM module in C and maintain it for all platforms vs using this workaround to get the job done, but with the convenience of using Go.

[Filippo Valsorda's post on building python modules with Go 1.5](https://blog.filippo.io/building-python-modules-with-go-1-5/) seems promising that Go 1.5 might be able to make this possible.

What's your read on this?  Could `go build -buildmode=c-shared` create a .so binary for vault-ssh-helpers  that could be called directly as a PAM module?  

Warm regards,
Steve

**Comment by vishalnayak** [comment]
@steve-jansen Before Go-1.5 was released, I had tried this option using 1.5 release candidate and had run into problems using the shared object. It was decided not to go with it until it works the way it should.

Creating shared objects using Go will be tried out again and if it works, it is the ideal thing to happen! This helper can itself be a PAM module instead of a command invoked by another PAM module.
