### ISSUE TITLE
Tokens issued via vault-ssh-helper OTP are not being revoked properly

### ISSUE THREAD

**Issue by jrdemasi** [hashicorp/vault-ssh-helper#40]
Currently, I am using SSH OTP to login to some CentOS 7 systems and everything is working as intended (or, at least, as I want them to :-)).  However, when I logout, I get output like the following, and tokens are not actually being revoked: 
```
[<sshuser>@hostname ~]$ exit
logout
Connection to xxx.xxx.xx.xx closed.
failed to revoke key: Error making API request.

URL: PUT https://mydomain.tld/v1/sys/leases/revoke/ssh/creds/<sshuser>/ArYTGUV78708q14rXXmNNrZg
Code: 403. Errors:

* 1 error occurred:
	* permission denied
```

If I manually add a policy to grant access to sys/leases/revoke/ssh/creds/* and apply it to my users, it works fine, but of course they can also revoke any tokens in the path then.  Shouldn't this be using auth/token/revoke-self?  Is there something I'm missing about the appropriate way to be using this? 

Thanks in advance!

**Comment by aram535** [comment]
I also just ran across this.  I rather not add revoke to all users.

**Comment by jrdemasi** [comment]
Yeah, I'm not convinced this is maintained or cared about. I've since just
written my own functionality to avoid using their ssh helper. :-/

**Comment by jefferai** [comment]
I don't think that's quite the same situation but @ncabatoff is right in that you probably don't want to revoke the token that generated the lease as then every time you SSHed somewhere you'd have to reauthenticate to Vault.

Given that lease IDs are not public and you'd have to know the exact lease ID to revoke it, most people simply grant access to sys/leases/revoke. Although it does look like we should update the bit in the SSH secrets engine to use the body form of the revoke call instead of the path form.
